### PR TITLE
Language dropdown: improvement for #108

### PR DESCRIPTION
**Pull request by Daniel-Leedan**
- Change background color
- Add box-shadow
- Remove border-radius
- Remove border on desktop

## Desktop

dropdown-d-gif

## Mobile

dropdown-m-gif

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
You have a merge conflict

**Comment by Daniel-Leedan** [comment]
@RocksteadyTC  I've tried again, hope it's better now.

**Comment by RocksteadyTC** [comment]
Cool thanks! Lets see how she looks

**Comment by Daniel-Leedan** [comment]
Great! Now it's perfect :)

**Pull request merged**
