### PR TITLE
i18n, unit tests, travis integration.

### PR DESCRIPTION
**Pull request by jerme404**

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
Needs to be merged again. Can't figure out how to un-revert a revert.  Resubmit PR if that's quicker than waiting for me to learn to fix the revert @jerme404

**Comment by jerme404** [comment]
No problem, I can resubmit.

**Comment by RocksteadyTC** [comment]
@jerme404 thanks just let me know when you're ready.

**Comment by jerme404** [comment]
@RocksteadyTC here ya go https://github.com/turtlecoin/turtlecoin.lol/pull/27

**Pull request merged**
