### PR TITLE
[WIP] Use metalsmith to better organize things

### PR DESCRIPTION
**Pull request by ac1984**
🚧 🚧 🚧 🚧 🚧 🚧 🐢 

1. [x] Setup [metalsmith](http://www.metalsmith.io).
2. [x] Move the current code to the right spots based on the project structure.
3. [ ] Evaluate using Webpack (🤕 ) or something else for better asset management.
4. [ ] Refactor to use layouts.
5. [ ] Tackle [brand](https://github.com/turtlecoin/turtlecoin.lol/tree/master/brand). (not sure what it is)

**FYI for later**
1. [ ] See whats to be done for deployment. Ultimately, we want to auto deploy on merges to `master`, along with a 'review' app per PR.
2. Setup linting, [editorconfig](http://editorconfig.org).

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
I'm curious what exactly is taking place here, at the current stage

**Comment by ac1984** [comment]
@RocksteadyTC While this static generation is one approach, the other approach would be a use full blown framework like EmberJS to do the same (since it includes the equivalent, and hence is much more streamlined). But that does increase the barrier to entry for beginners, I don't have a handle on our threshold for that.

Let me know what you think.

**Comment by RocksteadyTC** [comment]
I look forward to seeing the finished product, and your proposal in http://meta.turtlecoin.lol when you're ready to present it. Thanks for helping :)

**Comment by ac1984** [comment]
@RocksteadyTC Ah yes, I should have done that first! I'll do that before doing anything else.

**Comment by ac1984** [comment]
@RocksteadyTC Just so that I know, the probably in meta comes before an implementation/PR right?

**Comment by RocksteadyTC** [comment]
The involvement of non-static tools, generators, etc, would contradict some of our stated goals regarding inclusiveness and stewardship of junior devs where possible, however, this would be a great learning experience and entirely permissible should the entire workflow and tool chain be thoroughly  annotated with turtle-specific step by step documentation for those that follow in your steps.

I understand this extra documentation requirement is a hefty demand you may not be willing or able to accommodate, so in that event, I'd encourage you to enlist help for the documentation portion if that is not of interest or compatible with your schedule.

**Comment by RocksteadyTC** [comment]
The proposal in meta can happen whenever you'd like. Before, if you need help-- or After, if you need review. You may seek to enlist help with documenting your toolchain from Meta.

**Comment by ac1984** [comment]
Waiting on https://github.com/turtlecoin/meta/issues/47

**Comment by ac1984** [comment]
Closing as based on the linked meta discussion, a more approachable setup is needed for this project.

**Pull request closed without merging**
