### PR TITLE
Update README.md: Translations and contributors

### PR DESCRIPTION
**Pull request by Daniel-Leedan**
Update list of translations and contributors

image

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
Why is the bottom one crossed out?

**Comment by Daniel-Leedan** [comment]
The 'Hebrew' translation? 
The previous translation was done by @mrrovot, he still active so I moved him up to the active translation  list . 
Should I add him to the previous list as well?

**Comment by RocksteadyTC** [comment]
I think it is best to leave the previous list intact, and to create a new list above it, with nothing crossed out.

**Comment by Daniel-Leedan** [comment]
I got you. I added it back.

**Comment by RocksteadyTC** [comment]
Thanks :+1:

**Pull request merged**
