### PR TITLE
RU translation

### PR DESCRIPTION
**Pull request by stripalov**

### CODE REVIEW

**Comment by ar-x** [comment]
@stripalov Thanks for this. Can you find someone from the community to review your PR.

**Comment by ar-x** [comment]
@AkexBomg - FYI - you can directly comment on the line number. For example, go here:  https://github.com/turtlecoin/turtlecoin.lol/pull/48/files#diff-c81ec0e9b43fc7a5370100435ffa1adfR19, hover on the line number, and you'll see a `+` icon. Click it to comment.

**Comment by Jihadist** [comment]
Мемная фраза, в русскоязычном варианте звучит как "подержи мое пиво".
Одна проблема, в русском языке она не мемная

**Comment by CaptainMeatloaf** [comment]
As per my comment on discord, after reading the comment by @Jihadist, and looking at this translation, I think we should close this and focus on offering improvements to #45 as it reads much more naturally than this.

**Comment by ar-x** [comment]
Going to close this PR in favor of completing #45.

**Pull request closed without merging**
