### PR TITLE
kr.yml

### PR DESCRIPTION
**Pull request by seocal**
add korean translations

### CODE REVIEW

**Comment by ar-x** [comment]
@seocal Sorry for the delay on this. The final step is to get someone from the community to review your translations. Once done, it would be merged in.

**Comment by RocksteadyTC** [comment]
If they have github accounts sure, why not

**Comment by ar-x** [comment]
@seocal were you able to find someone?

**Comment by seocal** [comment]
hey I did find a couple of my friends who would
go through my translation.

we are planning to go about it as soon as possible, hopefully this weekend.

what would be the next step after they review it for me?

On Sep 14, 2018 3:29 AM, ar-x <notifications@github.com> wrote:

@seocal<https://github.com/seocal> were you able to find someone?

**Comment by seocal** [comment]
sorry I have no idea what I just did

I tried to delete the old ones but seems like i did something else stupid lol

btw, I have come up with the final version now, just had my friend review it.

**Pull request merged**
