### PR TITLE
RU translation

### PR DESCRIPTION
**Pull request by stripalov**

### CODE REVIEW

**Comment by ar-x** [comment]
@stripalov I just saw this PR. Maybe you could help out here: https://github.com/turtlecoin/turtlecoin.lol/pull/45?

**Comment by stripalov** [comment]
I think that my translation contains more official vocabulary and less jargonisms. In addition, I have a fairly large experience of translating into Russian in such a project as MIUI ROM However, both translations have a right to life and equally can be accepted

**Comment by ar-x** [comment]
@stripalov oh but you closed your PR. How can it be reviewed and merged now?

**Comment by CaptainMeatloaf** [comment]
@stripalov Perhaps you could do a review of the other commit and offer some pointers to the other committer on use of jargon, or alternatively offer some changes to that. It appears you have closed this pull request so it is not possible to do here.

**Pull request closed without merging**
