### PR TITLE
RTL Hebrew translation

### PR DESCRIPTION
**Pull request by mrrovot**

### CODE REVIEW

**Comment by ar-x** [comment]
@mrrovot Thanks. Can you get someone to review the translations? 

I'll also need to figure out the RTL support on the site.

**Comment by mrrovot** [comment]
I will try to get someone to review

**Comment by imperdin** [comment]
One of the issues with Hebrew is that it goes from Right to Left so sentences like  
 ```הצטרפו אלינו בgiithub```  
should be written as 
```Github הצטרפו אלינו ב```

**Comment by ar-x** [comment]
I'll check out the RTL thing in a bit. Thanks.

**Comment by Mineirofox** [comment]
Nice

**Comment by mrrovot** [comment]
```
One of the issues with Hebrew is that it goes from Right to Left so sentences like
הצטרפו אלינו בgiithub
should be written as
Github הצטרפו אלינו ב
```

@imperdin yes, this is due to me copy pasting into github and don't have hebrew formatting in my computer, please if you can fix the english letters to fit the rest of the hebrew?

It was written by a friend and submitted by me

**Pull request merged**
