### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by jerme404**
Add a new language simply by copying en.json in the languages folder, naming it to your language (es.json, de.json, etc) and running gulp build.

### CODE REVIEW

**Comment by jerme404** [comment]
This will use your browser language if it's one of the available languages.  Otherwise, it defaults to english.  If you select a language, it'll remember your language selection whenever you visit the site again.

**Comment by ar-x** [comment]
@RocksteadyTC @BebopTC super sorry to be late on this PR after so much work as been done :(. I was thinking that we should just keep things super simple on the marketing site. Adding Angular does raise the barrier to entry for other contributors. 

Is this the simplest way to add localization?

**Comment by RocksteadyTC** [comment]
Nothing to be sorry for, we're all outside cats :)

> Is this the simplest way to add localization? Would just adding Jekyll with one if its i18n integrations suffice?

I'd be inclined to lean on you for advice about Jekyll, but my experiences with it so far lead me to believe that yes it'd be easier than Angular

**Comment by jerme404** [comment]
Yeah, it's not a ton of work, I spent a few hours doing it.  I just used Angular because I didn't like any of the pre-built options I found, and using gulp it was easy to compile all of the language files into a single tiny file, so the client doesn't have to pull in languages from server, so switching languages is incredibly fast.

It's actually super simple to work with, but in my experience, the biggest downside to my approach is that you have to maintain all of the language files, so more attention to detail is needed when updating the site.  But it's how I usually do enterprise products when we have teams of BA/QA resources to manage that stuff for us.

**Comment by jerme404** [comment]
I just looked at jekyll, and it looks like it's doing pretty much the same thing that I did, but using ruby instead of angular?  https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

**Comment by ar-x** [comment]
Yes the net thing is the same. I am thinking that more developers are familiar with Jekyll than Angular. Frontend frameworks can be a touch topic ;), and IMHO avoided if not needed. 

Anyways – I think @BebopTC knows both sides, so I'll leave it to him to decide. My **main** intent here is to keep the project as accessible to developers as possible. I'm not picky on the method used to achieve that.

>  you have to maintain all of the language files

I suppose we could write a test to assert that all translation keys have values in all translation files.

**Comment by RocksteadyTC** [comment]
If we have an abundance of overlap with Angular, skill-wise, then it makes sense to use Angular rather than forcing Jekyll for being the wider-known tool outside of our circle. I suppose if we do Angular we can always consider a convo about Option X when a vocal crowd of Option X supporters appears.

Personally, I'm not recently familiar with Angular 2+, but it doesn't make sense for me to get in the way of work that needs to be done anyway, in the name of a more popular too, for something that needs doing urgently anyway regardless of the method.

If you guys both understand Angular, let's just roll it out and see what happens.

**Comment by RocksteadyTC** [comment]
image

**Comment by ar-x** [comment]
I've done react, ember, elm before, just not angular .. though all frameworks start looking the same after a while ;)

**Comment by jerme404** [comment]
And the code part is already done, so so make any changes to the site, you don't really need to have angular experience anyway, unless we want to do more with it.

**Pull request closed without merging**
