### PR TITLE
Update main.css: REMOVED footer margin on mobile

### PR DESCRIPTION
**Pull request by Daniel-Leedan**
footer-gif

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
Hey thanks for catching that. How does it effect desktop and tablet views?

**Comment by Daniel-Leedan** [comment]
@RocksteadyTC The PR effect only on screens that are 736px or less,  It doesn't effect desktop and tablet views.

```CSS
@media` screen and (max-width: 736px) {
...
}

**Comment by RocksteadyTC** [comment]
Cool, thanks :)

**Comment by RocksteadyTC** [comment]
Let us know if you join the discord chat and Ill add your developer role.

**Comment by Daniel-Leedan** [comment]
> Let us know if you join the discord chat and Ill add your developer role.

I'm there! Daniel_Leedan#9378 :)

**Pull request merged**
